spring.application.name=IT211Project

# Datasource H2
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:dbtest;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT
jwt.secret=ThisIsASecretKeyForJWTThisIsASecretKeyForJWTThisIsASecretKeyForJWT
jwt.expiration=3600000
jwt.refresh_expiration=2592000000

# Upload
imageUploadDir=uploads/

# Cloudinary (fake value cho test)
cloudinary.cloud-name=test
cloudinary.api-key=test
cloudinary.api-secret=test